# -*- coding: utf-8 -*-
"""Pertemuan 9 - Chatbot RAG.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ajIZmonUk9bNy6Fu987C36WVWRIMR2iv

# MEMBANGUN CHATBOT RAG SEDERHANA
"""

!pip install qdrant-client sentence-transformers

from qdrant_client import QdrantClient
from qdrant_client.models import Distance, VectorParams, PointStruct
from sentence_transformers import SentenceTransformer

# 1. Memuat model penyematan (Embedding Model)
print("Memuat model penyematan...")
model = SentenceTransformer('paraphrase-multilingual-MiniLM-L12-v2')

# 2. Inisialisasi Qdrant di dalam memori lokal
client = QdrantClient(":memory:")

# 3. Membuat koleksi (tabel) di Qdrant
# Model MiniLM menghasilkan vektor berdimensi 384
client.create_collection(
    collection_name="basis_pengetahuan",
    vectors_config=VectorParams(size=384, distance=Distance.COSINE),
)
print("Koleksi Qdrant berhasil dibuat!")

# Contoh dokumen internal
dokumen = [
    "Universitas Harkat Negeri (UHN) memiliki fakultas unggulan di bidang Teknologi Informasi dan Kecerdasan Buatan.",
    "Politeknik Harapan Bersama (Poltek Harber) Tegal berfokus pada pendidikan vokasi yang terintegrasi erat dengan industri.",
    "Mahasiswa tingkat akhir diwajibkan menyelesaikan proyek tugas akhir berupa rancang bangun perangkat lunak atau implementasi Machine Learning."
]

# Mengubah teks menjadi vektor dan memasukkannya ke Qdrant
points = []
for i, teks in enumerate(dokumen):
    vektor = model.encode(teks).tolist()
    points.append(
        PointStruct(id=i, vector=vektor, payload={"teks_asli": teks})
    )

# Menyimpan ke database
client.upsert(
    collection_name="basis_pengetahuan",
    points=points
)
print("Data berhasil disimpan ke Vector Database!")

# Blok Kode 4: Proses Retrieval (Revisi API Qdrant Terbaru)
pertanyaan_user = "Di mana saya bisa belajar pendidikan vokasi yang terhubung dengan industri?"

# Ubah pertanyaan menjadi vektor
vektor_query = model.encode(pertanyaan_user).tolist()

# Cari 1 dokumen yang paling relevan di Qdrant menggunakan query_points
hasil_pencarian = client.query_points(
    collection_name="basis_pengetahuan",
    query=vektor_query,
    limit=1
).points  # Tambahkan .points untuk mengambil list datanya

# Memastikan ada hasil yang dikembalikan sebelum mencetaknya
if hasil_pencarian:
    konteks_ditemukan = hasil_pencarian[0].payload["teks_asli"]
    skor_kemiripan = hasil_pencarian[0].score

    print(f"Pertanyaan: {pertanyaan_user}")
    print(f"Konteks relevan ditemukan (Skor {skor_kemiripan:.4f}): {konteks_ditemukan}")
else:
    print("Tidak ada konteks yang relevan ditemukan.")

prompt_akhir = f"""
Anda adalah asisten AI yang bertugas menjawab pertanyaan berdasarkan konteks yang diberikan.
Jika jawabannya tidak ada di dalam konteks, katakan bahwa Anda tidak tahu.

Konteks:
{konteks_ditemukan}

Pertanyaan:
{pertanyaan_user}

"""

print("\n--- PROMPT YANG AKAN DIKIRIM KE LLM ---")
print(prompt_akhir)